# docker-compose.yml - Composition of micro-services to run OpenDLV software.
# Copyright (C) 2016 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2016-10-13

version: '2'

services:
    odsupercomponent:
        build: .
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"

    # microservice for action-communicate
    action-communicate:
        build: .
        network_mode: "host"
        working_dir: "/opt/opendlv/bin"
        restart: always
        depends_on:
            - odsupercomponent
        command: "/opt/opendlv/bin/opendlv-system-application-action-communicate --cid=${CID}"

    # microservice for knowledge-gcdc16-rule-intersection-host
    knowledge-gcdc16-rule-intersection-host:
        build: .
        network_mode: "host"
        working_dir: "/opt/opendlv/bin"
        restart: always
        depends_on:
            - odsupercomponent
        command: "/opt/opendlv/bin/opendlv-system-application-knowledge-gcdc16-rule-intersectionhost --cid=${CID} --freq=10"

    # microservice for knowledge-gcdc16-v2viclcm
    knowledge-gcdc16-v2viclcm:
        build: .
        network_mode: "host"
        working_dir: "/opt/opendlv/bin"
        restart: always
        depends_on:
            - odsupercomponent
        command: "/opt/opendlv/bin/opendlv-system-application-knowledge-gcdc16-v2viclcm --cid=${CID} --freq=10"

    # microservice for knowledge-identity
    knowledge-identity:
        build: .
        network_mode: "host"
        working_dir: "/opt/opendlv/bin"
        restart: always
        depends_on:
            - odsupercomponent
        command: "/opt/opendlv/bin/opendlv-system-application-knowledge-identity --cid=${CID} --freq=1"

    # microservice for knowledge-linguistics-v2vcam
    knowledge-linguistics-v2vcam:
        build: .
        network_mode: "host"
        working_dir: "/opt/opendlv/bin"
        restart: always
        depends_on:
            - odsupercomponent
        command: "/opt/opendlv/bin/opendlv-system-application-knowledge-linguistics-v2vcam --cid=${CID} --freq=25"

    # microservice for sensation-audition
    sensation-audition:
        build: .
        network_mode: "host"
        working_dir: "/opt/opendlv/bin"
        restart: always
        depends_on:
            - odsupercomponent
        command: "/opt/opendlv/bin/opendlv-system-application-sensation-audition --cid=${CID}"

    # micro service for proxy-roadscape.
    proxy-roadscape:
        build: .
        image: chalmersrevere/copplar-core-on-opendlv-core-on-opendavinci-ubuntu-16.04-complete:latest
#       image: seresearch/copplar-core-on-opendlv-core-on-opendavinci-ubuntu-16.04:latest
        network_mode: "host"
        devices:
        - "/dev/pcan32:/dev/pcanusb0"
        depends_on:
            - odsupercomponent
        command: "/opt/copplar.core/bin/opendlv-core-system-proxy-roadscape --cid=${CID}"
    
    # microservice for proxy-v2v
    proxy-v2v:
        build: .
        network_mode: "host"
        working_dir: "/opt/opendlv.core/bin"
        restart: always
        depends_on:
            - odsupercomponent
        command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-v2v --cid=${CID}"
